#!/bin/sh
 
function untilsuccessful() {
	"$@"
	while [ $? -ne 0 ]; do
		echo Retrying...
		sleep 1
		"$@"
	done
}

IP=`hostname --ip-address`
SEED=$1

# Start Couchbase
/etc/init.d/couchbase-server start

# Init Couchbase
if [ -n "$SEED" ]; then
	echo "Starting Couchbase ($IP) and joining cluster via $SEED"
	untilsuccessful couchbase-cli server-add -c $SEED \
		--user=$CB_USERNAME --password=$CB_PASSWORD \
		--server-add=$IP
else
	echo "Starting Couchbase ($IP) as new cluster"
	untilsuccessful couchbase-cli cluster-init -c $IP \
		--cluster-init-username=$CB_USERNAME \
		--cluster-init-password=$CB_PASSWORD
fi

# Start watchdog on server status
couchbase-watch
